/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health probe with DB latency tier */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service healthy or degraded (still serving traffic). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthBody'];
          };
        };
        /** @description Service down: DB unreachable. */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthBody'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Start Google OAuth (PKCE) flow */
    get: {
      parameters: {
        query?: {
          redirect?: string;
          tz?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect */
        302: {
          headers: {
            Location?: string;
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** OAuth callback: exchange code, create session, redirect to FE */
    get: {
      parameters: {
        query?: {
          code?: string;
          state?: string;
          error?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect */
        302: {
          headers: {
            Location?: string;
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user from session cookie */
    get: {
      parameters: {
        query?: never;
        header?: {
          'x-client-timezone'?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: components['schemas']['User'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke session and clear cookie */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              ok: true;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update current user (timezone, locale) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserInput'];
        };
      };
      responses: {
        /** @description Updated user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: components['schemas']['User'];
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/habits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List habits for current user */
    get: {
      parameters: {
        query?: {
          archived?: 'true' | 'false';
          sort?: 'created' | 'sort_order';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of habits */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              habits: components['schemas']['Habit'][];
            };
          };
        };
      };
    };
    put?: never;
    /** Create a habit */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateHabitInput'];
        };
      };
      responses: {
        /** @description Created habit */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              habit: components['schemas']['Habit'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/habits/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get habit by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Habit */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              habit: components['schemas']['Habit'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete habit (cascade entries) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              ok: true;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update habit */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateHabitInput'];
        };
      };
      responses: {
        /** @description Updated habit */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              habit: components['schemas']['Habit'];
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/habits/{id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Toggle archived state for habit */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Habit after archive toggle */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              habit: components['schemas']['Habit'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/habits/{id}/entries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List entries for habit in date range */
    get: {
      parameters: {
        query: {
          from: string;
          to: string;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Entries in range */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              entries: components['schemas']['Entry'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/habits/{id}/entries/{date}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Upsert entry for habit on date */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          date: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpsertEntryInput'];
        };
      };
      responses: {
        /** @description Upserted entry */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              entry: components['schemas']['Entry'];
            };
          };
        };
      };
    };
    post?: never;
    /** Delete entry for habit on date */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          date: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              ok: true;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/habits/{id}/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get streak and completion stats for a habit */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Habit stats */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HabitStats'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/habits/{id}/heatmap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get heatmap cells for a habit in date range */
    get: {
      parameters: {
        query: {
          from: string;
          to: string;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Heatmap cells */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HeatmapResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stats/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get dashboard summary for all active habits */
    get: {
      parameters: {
        query?: {
          period?: '7d' | '30d' | '90d' | '365d';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dashboard summary */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DashboardSummary'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stats/completion-trend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get daily completion trend */
    get: {
      parameters: {
        query?: {
          period?: '7d' | '30d' | '90d' | '365d';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Completion trend */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CompletionTrend'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stats/weekday-breakdown': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get completion breakdown by weekday */
    get: {
      parameters: {
        query?: {
          period?: '7d' | '30d' | '90d' | '365d';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Weekday breakdown */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WeekdayBreakdown'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/today': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get today's habit list with due status and entries */
    get: {
      parameters: {
        query?: {
          date?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Today items */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TodayResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthBody: {
      ok: boolean;
      /** @enum {string} */
      db: 'ok' | 'degraded' | 'down';
      dbLatencyMs: number;
      uptime: number;
      version: string;
    };
    User: {
      id: string;
      /** Format: email */
      email: string;
      name: string;
      avatarUrl: string | null;
      timezone: string;
      /** @enum {string} */
      locale: 'ru' | 'en';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateUserInput: {
      timezone?: string;
      /** @enum {string} */
      locale?: 'ru' | 'en';
    };
    Habit: {
      id: string;
      title: string;
      description: string | null;
      color: string;
      icon: string | null;
      /** @enum {string} */
      kind: 'boolean' | 'counter';
      targetPerDay: number;
      /** @enum {string} */
      frequency: 'daily' | 'weekdays' | 'weekends' | 'custom';
      customDays: number[] | null;
      reminderTime: string | null;
      sortOrder: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      archivedAt: string | null;
    };
    CreateHabitInput: {
      title: string;
      description?: string | null;
      color: string;
      icon?: string | null;
      /** @enum {string} */
      kind: 'boolean' | 'counter';
      targetPerDay?: number;
      /** @enum {string} */
      frequency: 'daily' | 'weekdays' | 'weekends' | 'custom';
      customDays?: number[] | null;
      reminderTime?: string | null;
      sortOrder?: number;
    };
    UpdateHabitInput: {
      title?: string;
      description?: string | null;
      color?: string;
      icon?: string | null;
      /** @enum {string} */
      kind?: 'boolean' | 'counter';
      targetPerDay?: number;
      /** @enum {string} */
      frequency?: 'daily' | 'weekdays' | 'weekends' | 'custom';
      customDays?: number[] | null;
      reminderTime?: string | null;
      sortOrder?: number;
    };
    Entry: {
      id: string;
      habitId: string;
      date: string;
      count: number;
      note: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpsertEntryInput: {
      count: number;
      note?: string | null;
    };
    HabitStats: {
      currentStreak: number;
      bestStreak: number;
      completionRate: number;
      totalCompleted: number;
      totalDue: number;
    };
    HeatmapResponse: {
      cells: components['schemas']['HeatmapCell'][];
    };
    HeatmapCell: {
      date: string;
      count: number;
      level: 0 | 1 | 2 | 3 | 4;
    };
    DashboardSummary: {
      /** @enum {string} */
      period: '7d' | '30d' | '90d' | '365d';
      activeHabits: number;
      avgCompletionRate: number;
      habits: {
        habitId: string;
        title: string;
        completionRate: number;
        currentStreak: number;
      }[];
    };
    CompletionTrend: {
      /** @enum {string} */
      period: '7d' | '30d' | '90d' | '365d';
      data: {
        date: string;
        doneCount: number;
        dueCount: number;
        rate: number;
      }[];
    };
    WeekdayBreakdown: {
      /** @enum {string} */
      period: '7d' | '30d' | '90d' | '365d';
      data: {
        weekday: number;
        doneCount: number;
        dueCount: number;
        rate: number;
      }[];
    };
    TodayResponse: {
      date: string;
      items: components['schemas']['TodayItem'][];
    };
    TodayItem: {
      habitId: string;
      title: string;
      color: string;
      icon: string | null;
      kind: string;
      targetPerDay: number;
      frequency: string;
      isDue: boolean;
      entry: components['schemas']['TodayEntry'];
    };
    TodayEntry: {
      count: number;
      note: string | null;
    } | null;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
